name = "Pilot"
uuid = "ae4e50cc-6dbb-4f20-9f13-c46e7dac87e8"
authors = ["yngtodd"]
version = "0.1.0"

[compat]
julia = "1.4"

[deps]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
